# This workflow will build and push a Python application to an Azure Web App when a commit is pushed to your default branch.
# This workflow assumes you have already created the target Azure App Service web app and a repository secret AZURE_WEBAPP_PUBLISH_PROFILE exists, containing the app's Publish Profile.
# Make your the AZURE_WEBAPP_NAME environment variable below, contains the web app's name.

name: Build, test, and deploy a Python app to Azure Web App
env:
  AZURE_WEBAPP_NAME: "webApp-rh5dsxbm77scq" # <<< Azure Web App name
  PYTHON_VERSION: "3.12"

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python version
        uses: actions/setup-python@v5.1.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: "pip"

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          pip install -r tests/requirements.txt
          pip install -r ./requirements.txt

      - name: Lint with autopep8
        run: |
          autopep8 --exit-code --recursive --diff --aggressive --aggressive ./src
  
      - name: Fail if autopep8 made changes
        if: steps.autopep8.outputs.exit-code == 2
        run: exit 1

      - name: Test with pytest
        run: pytest

      - name: Fail if tests failed
        if: ${{ failure() && steps.test_step.outcome == 'failure' }}
        run: exit 1

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            .
            !venv/
            !tests/
            !*/__pycache__

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
          path: .

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          restart: true