# This workflow will build and push a Python application to an Azure Web App when a commit is pushed to your default branch.
# This workflow assumes you have already created the target Azure App Service web app and a repository secret AZURE_WEBAPP_PUBLISH_PROFILE exists, containing the app's Publish Profile.
# Make your the AZURE_WEBAPP_NAME environment variable below, contains the web app's name.

name: azure-publish
env:
  AZURE_WEBAPP_NAME: "webApp-rh5dsxbm77scq" # <<< Azure Web App name
  PYTHON_VERSION: "3.12"

on:
  workflow_run:
    workflows: [ run-tests ]
    types:
      - completed
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            .
            !venv/
            !tests/
            !*/__pycache__

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
          path: .

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          restart: true